name: 'Run Test'

on:
  workflow_dispatch:
    inputs:
      use_modules_from_terraform_registry:
        type: boolean
        required: false

env:
  TF_CLI_ARGS: "-no-color"
  TF_INPUT: 0

permissions:
  contents: read

jobs:
  test_1:
    runs-on: ubuntu-latest
    environment: test

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:

      - name: Print GitHub Actions Context
        run: | 
          echo "${{ toJson(github) }}"
          echo "${{ toJson(job) }}"

      - name: Print GitHub link
        run: | 
          echo "Job Link: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ github.job }}"