name: 'Run Test'

on:
  workflow_dispatch: {}
#  push:
#    branches:
#      - 'add_tests'

env:
  TF_CLI_ARGS: "-no-color"
  TF_INPUT: 0
  TF_VAR_gw_count: 1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGE }}
  JUMP_SERVER_KEY: ${{ secrets.JUMP_SERVER_KEY }}
  TF_WORKSPACE: single_account

permissions:
  contents: read

jobs:
  terraform:

    strategy:
      max-parallel: 1
      matrix:
        include:
          - name: single account
            example_dir: ./examples/installation/sonar_multi_account_deployment


    name: '${{ matrix.name }}'
    runs-on: ubuntu-latest
    env:
      EXAMPLE_DIR: ./${{ matrix.example_dir }}
    environment: test

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Setup jq
      uses: sergeysova/jq-action@v2

    - name: Get The Public IP
      run: echo curr_ip=$(curl -s https://ipinfo.io/ip) >> $GITHUB_ENV

    - name: Set IP in AWS Security Group
      run: |
        aws_sg=$(aws ec2 authorize-security-group-ingress --group-id ${{ vars.JUMP_SERVER_SG_ID }} --protocol tcp --port 22 --cidr $curr_ip/32)
        echo sg_id=$(echo $aws_sg | jq '.SecurityGroupRules[0].SecurityGroupRuleId') >> $GITHUB_ENV

    # Checkout the repository to the GitHub Actions runner
    - name: Test connection
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 54.179.25.83
        username: ec2-user
        key: ${{ env.JUMP_SERVER_KEY }}
        port: 22
        command_timeout: "2h"
        envs: TF_VAR_gw_count,TF_WORKSPACE
        script: |
          echo "ws: $TF_WORKSPACE, gwc: $TF_VAR_gw_count"

    - name: Delete Security Group
      if: always()
      run: aws ec2 revoke-security-group-ingress --group-id ${{ vars.JUMP_SERVER_SG_ID }} --security-group-rule-ids ${{ env.sg_id }}

